// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5hw4lIbsyBRBuTcsOobU3Qpgkh2uNhLE',
    appId: '1:807891627705:android:7c052c80255d892b603568',
    messagingSenderId: '807891627705',
    projectId: 'ecowatch-67ca0',
    storageBucket: 'ecowatch-67ca0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApv9oTEsKsnS__5ZlEtqzdoaAVJ-xY1ZA',
    appId: '1:807891627705:ios:cf05670be4da7092603568',
    messagingSenderId: '807891627705',
    projectId: 'ecowatch-67ca0',
    storageBucket: 'ecowatch-67ca0.firebasestorage.app',
    iosClientId: '807891627705-aamo2t68s7hfqjs3amthnrige1k48qd1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecowatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApv9oTEsKsnS__5ZlEtqzdoaAVJ-xY1ZA',
    appId: '1:807891627705:ios:cf05670be4da7092603568',
    messagingSenderId: '807891627705',
    projectId: 'ecowatch-67ca0',
    storageBucket: 'ecowatch-67ca0.firebasestorage.app',
    iosClientId: '807891627705-aamo2t68s7hfqjs3amthnrige1k48qd1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecowatch',
  );
}
